# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  birdbox:
    image: birdbox
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5266:5001
    restart: unless-stopped
    environment:
     - PULSE_SERVER=unix:/run/user/1000/pulse/native=value
    volumes:
     - /run/user/1000/pulse/native:/run/user/1000/pulse/native
     - ./Data:/app/Data