// <auto-generated />
using System;
using Bird_Box.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bird_Box.Migrations
{
    [DbContext(typeof(BirdBoxContext))]
    [Migration("20231024091207_NewResultsModel")]
    partial class NewResultsModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("Bird_Box.Audio.Microphone", b =>
                {
                    b.Property<string>("objId")
                        .HasColumnType("TEXT");

                    b.Property<string>("deviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("deviceInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("objId");

                    b.ToTable("InputDevices");
                });

            modelBuilder.Entity("Bird_Box.Models.IdentifiedBird", b =>
                {
                    b.Property<string>("objId")
                        .HasColumnType("TEXT");

                    b.Property<string>("birdName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("detectionThreshold")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("recodingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("recordingDeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("objId");

                    b.ToTable("BirdRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
