// <auto-generated />
using Bird_Box.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace Bird_Box.Migrations
{
    [DbContext(typeof(BirdBoxContext))]
    partial class BirdBoxContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("Bird_Box.Audio.Microphone", b =>
                {
                    b.Property<string>("objId")
                        .HasColumnType("TEXT");

                    b.Property<string>("deviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("deviceInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("objId");

                    b.ToTable("InputDevices");
                });

            modelBuilder.Entity("Bird_Box.Models.IdentifiedBird", b =>
                {
                    b.Property<string>("objId")
                        .HasColumnType("TEXT");

                    b.Property<string>("birdName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("detectionThreshold")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("recodingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("recordingDeviceobjId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("objId");

                    b.HasIndex("recordingDeviceobjId");

                    b.ToTable("BirdRecords");
                });

            modelBuilder.Entity("Bird_Box.Models.IdentifiedBird", b =>
                {
                    b.HasOne("Bird_Box.Audio.Microphone", "recordingDevice")
                        .WithMany()
                        .HasForeignKey("recordingDeviceobjId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("recordingDevice");
                });
#pragma warning restore 612, 618
        }
    }
}
