// <auto-generated />
using System;
using Bird_Box.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bird_Box.Migrations
{
    [DbContext(typeof(BirdBoxContext))]
    partial class BirdBoxContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("Bird_Box.Models.IdentifiedBird", b =>
                {
                    b.Property<Guid>("objId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("birdName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("detectionThreshold")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("recodingDate")
                        .HasColumnType("TEXT");

                    b.HasKey("objId");

                    b.ToTable("BirdRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
