name: publish

on:
  push:
    branches: [ main ]

env:
  DOTNET_VERSION: '7.0.x' # The .NET SDK version to use

jobs:
  publish:

    runs-on: linux-arm64

    steps:
      - uses: actions/checkout@v3
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore
      
      - name: Publish
        run: dotnet publish -r linux-arm64 --self-contained true -o ./arm64

      - name: Create SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_HOST }}" > ~/.ssh/known_hosts
      
      - name: Deploy with rsync
        run: rsync -rav --delete build/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/projects/Bird-Box/
