name: publish

on:
  push:
    branches: [ main ]

env:
  DOTNET_VERSION: '7.0.x' # The .NET SDK version to use

jobs:
  publish:

    runs-on: linux-arm64

    steps:
    - name: Create directory for code
      run: |
        if test -f "~/gitea"; then
          echo "Directory already exist"          
        else
          mkdir "gitea"
        fi 

    - name: Create temp directory for code
      run: |
        if test -f "~/gitea/temp"; then
          echo "Temp directory already exist"          
        else
          cd ~/gitea
          mkdir "temp"
        fi 

    - name: Clone repo
      run: |
        git clone https://git.containercat.com/m918/Bird-Box.git ~/gitea/temp
        if test -f "~/gitea/Bird-Box"; then
          echo "Bird-Box directory already exist"          
        else
          mkdir "Bird-Box"
        fi 
        mv -v temp/* Bird-Box/
        rm -rf temp/* 
    
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: |
        cd ~/gitea/projects/Bird-Box
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release -o ../Bird-Box-linux-arm64 -r linux-arm64 --self-contained true /p:UseAppHost=true
      
    - name: Deploy to server
      uses: https://gitea.com/aquelle1/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i --delete"
        SOURCE: "~/gitea/projects/Bird-Box-arm64"
        REMOTE_HOST: ${{ secrets.SSH_HOST }}
        REMOTE_USER: ${{ secrets.SSH_USER }}
        TARGET: ${{ secrets.SSH_DIR }}