name: publish

on:
  push:
    branches: [ main ]

env:
  DOTNET_VERSION: '7.0.x' # The .NET SDK version to use

jobs:
  publish:

    runs-on: linux-arm64

    steps:
    - name: Create directory for code
      run: |
        mkdir -p "gitea"

    - name: Create temp directory for code
      run: |
        cd ~/gitea
        mkdir -p temp

    - name: Clone repo
      run: |
        git clone https://git.containercat.com/m918/Bird-Box.git ~/gitea/temp
        mkdir -p Bird-Box
        
    - name: Move code to  new folder
      run: |
        mv -u temp/* Bird-Box/
        rm -rf temp/ 

    - name: Create necessary folders
      run: |
        cd Bird-Box/
        mkdir -p Data
        mkdir -p Recordings

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: |
        cd ~/gitea/projects/Bird-Box
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release -o ../Bird-Box-linux-arm64 -r linux-arm64 --self-contained true /p:UseAppHost=true
      
    - name: Deploy to server
      uses: https://gitea.com/aquelle1/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i --delete"
        SOURCE: "~/gitea/projects/Bird-Box-arm64"
        REMOTE_HOST: ${{ secrets.SSH_HOST }}
        REMOTE_USER: ${{ secrets.SSH_USER }}
        TARGET: ${{ secrets.SSH_DIR }}
