name: publish

on:
  push:
    branches: [ main ]

env:
  DOTNET_VERSION: '7.0.x' # The .NET SDK version to use

jobs:
  publish:

    runs-on: linux-arm64

    steps:
      - uses: actions/checkout@v3
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore
      
      - name: Publish
        run: dotnet publish -r linux-arm64 --self-contained true
      
      - name: Deploy to server
        uses: https://gitea.com/aquelle1/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "~/gitea/projects/Bird-Box/Bird-Box-linux-arm64"
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          TARGET: ${{ secrets.SSH_DIR }}
