name: publish

on:
  push:
    branches: [ main ]

env:
  DOTNET_VERSION: '7.0.x' # The .NET SDK version to use

jobs:
  publish:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
  
      - name: Create installation cache
        run: apt-get update

      - name: Install zip package
        run:  apt-get install add zip -y

      - name: Install rsync and ssh packages
        run:  apt-get install rsync openssh-client -y

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore
      
      - name: Publish
        run: dotnet publish -r linux-x64 --self-contained true -o ./linux-x64

      - name: Create necessary folders
        run: |
          cd linux-x64
          mkdir Data
          mkdir Recordings
          cd ..
          pwd

      - name: Create zip archive
        run: |
          zip -r Bird-Box-linux-x64.zip linux-x64
      
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_STORAGE_PRIVATE_KEY }}
          ARGS: "-avz -i --delete"
          SOURCE: "Bird-Box-linux-x64.zip"
          REMOTE_HOST: ${{ secrets.SSH_STORAGE_HOST }}
          REMOTE_USER: ${{ secrets.SSH_STORAGE_USER }}
          TARGET: ${{ secrets.SSH_ZIP_DIR }}
